# Urban Mobility Analytics — Exploratory Data Analysis

## Objective

The objective of this analysis is to understand urban mobility
patterns using pickup date, time, weekday, weekend, and pickup
location information.

## Key Questions

1. When does pickup demand peak?
2. How does demand vary by hour?
3. How does demand differ between weekdays and weekends?
4. Which days of the week have the highest demand?
5. How does demand vary across months?
6. Which pickup locations contribute the most trips?
7. Are there unusual patterns or outliers?

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


from sqlalchemy import create_engine   # ✅ sahi (underscore)

print("All import are working fine")

All import are working fine

In [29]:
USERNAME = "abhishekmahto"
PASSWORD = "PASSWORD"
HOST = "localhost"
PORT = "5432"
DATABASE = "urban_mobility_analytics"

engine = create_engine(
    f"postgresql+psycopg2://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
)

print("Database connection successfully established!")

Database connection successfully established!

In [30]:
with engine.connect():
    print("Connected to the database successfully!")

    query = """
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public';
    """

    tables_df = pd.read_sql(query, engine)

    print("\nTables in Database:")
    print(tables_df)

    first_table = tables_df["table_name"].iloc[0]

    print(f"\nLoading Table: {first_table}")

Connected to the database successfully!

Tables in Database:
                         table_name
0             other_american_b01362
1               uber_raw_data_apr14
2                 uber_jan_feb_foil
3            other_highclass_b01717
4               uber_raw_data_aug14
5               uber_raw_data_sep14
6               uber_raw_data_jul14
7               other_federal_02216
8               uber_raw_data_jun14
9               other_carmel_b00256
10               other_diplo_b01196
11               other_dial7_b00887
12              uber_raw_data_may14
13            other_prestige_b01338
14                other_lyft_b02510
15  other_fhv_services_jan_aug_2015
16          other_firstclass_b01536
17             other_skyline_b00111
18         uber_raw_data_janjune_15

Loading Table: other_american_b01362

In [31]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
"""

tables_df = pd.read_sql(query, engine)

print("\nTables in Database:")
print(tables_df)

Tables in Database:
                         table_name
0             other_american_b01362
1               uber_raw_data_apr14
2                 uber_jan_feb_foil
3            other_highclass_b01717
4               uber_raw_data_aug14
5               uber_raw_data_sep14
6               uber_raw_data_jul14
7               other_federal_02216
8               uber_raw_data_jun14
9               other_carmel_b00256
10               other_diplo_b01196
11               other_dial7_b00887
12              uber_raw_data_may14
13            other_prestige_b01338
14                other_lyft_b02510
15  other_fhv_services_jan_aug_2015
16          other_firstclass_b01536
17             other_skyline_b00111
18         uber_raw_data_janjune_15

In [32]:
first_table = tables_df["table_name"].iloc[0]

print(f"\nLoading Table: {first_table}")

Loading Table: other_american_b01362

In [33]:
query = f'SELECT * FROM "{first_table}";'

df = pd.read_sql(query, engine)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (91712, 6)

In [34]:
df.head()

,DATE,TIME,PICK UP ADDRESS,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,7/1/2014,12:00:00 AM,"874 E 139th St Mott Haven, BX",None,None,None
1,7/1/2014,12:01:00 AM,"628 E 141st St Mott Haven, BX",None,None,None
2,7/1/2014,12:01:00 AM,"601 E 156th St South Bronx, BX",None,None,None
3,7/1/2014,12:01:00 AM,"708 E 138th St Mott Haven, BX",None,None,None
4,7/1/2014,12:02:00 AM,"700 E 140th St Mott Haven, BX",None,None,None

In [35]:
df.columns.tolist()

['DATE', 'TIME', 'PICK UP ADDRESS', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5']

In [36]:
print("=" * 60)
print("DATASET OVERVIEW")
print("=" * 60)

print(f"\nRows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

============================================================
DATASET OVERVIEW
============================================================

Rows    : 91,712
Columns : 6

Column Names:
['DATE', 'TIME', 'PICK UP ADDRESS', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5']

Data Types:
DATE               object
TIME               object
PICK UP ADDRESS    object
Unnamed: 3         object
Unnamed: 4         object
Unnamed: 5         object
dtype: object

In [37]:
missing = df.isnull().sum()

missing_report = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": (
        missing / len(df) * 100
    ).round(2)
})

missing_report = missing_report[
    missing_report["Missing_Count"] > 0
].sort_values(
    "Missing_Percentage",
    ascending=False
)

display(missing_report)

            Missing_Count  Missing_Percentage
Unnamed: 3          91712               100.0
Unnamed: 4          91712               100.0
Unnamed: 5          91712               100.0

In [38]:
duplicate_count = df.duplicated().sum()

print(f"Duplicate rows: {duplicate_count:,}")
print(
    f"Duplicate percentage: "
    f"{duplicate_count / len(df) * 100:.2f}%"
)

Duplicate rows: 588
Duplicate percentage: 0.64%

In [39]:
df.describe()

,DATE,TIME,PICK UP ADDRESS,Unnamed: 3,Unnamed: 4,Unnamed: 5
count,91712,91712,91712,0,0,0
unique,92,1440,10608,0,0,0
top,9/13/2014,7:39:00 AM,"400 Brook Ave Mott Haven, BX",NaN,NaN,NaN
freq,1440,120,1216,NaN,NaN,NaN

In [40]:
df.describe(include="object")

,DATE,TIME,PICK UP ADDRESS,Unnamed: 3,Unnamed: 4,Unnamed: 5
count,91712,91712,91712,0,0,0
unique,92,1440,10608,0,0,0
top,9/13/2014,7:39:00 AM,"400 Brook Ave Mott Haven, BX",NaN,NaN,NaN
freq,1440,120,1216,NaN,NaN,NaN

In [42]:
print(df.columns.tolist())

['DATE', 'TIME', 'PICK UP ADDRESS', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5']

In [47]:
import sys
sys.path.append("../src")

In [48]:
from profile_data import load_data, clean_dataset

In [49]:
df = load_data(engine, first_table)

In [50]:
cleaned_df = clean_dataset(df)

==================================================
CLEANING DATASET
==================================================
/n Removing the empty columns
Index(['Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5'], dtype='object')

 Shape of the dataset after removing the empty columns:
(91712, 3)

 Number of duplicated rows: 588

 Rows after removing duplicates : 91124

 Datatype after conversion:
DATE               datetime64[ns]
TIME                       object
PICK UP ADDRESS            object
dtype: object

 = * 50

 Final Validation of the dataset after cleaning and feature engineering:
(91124, 17)

 final datatypes: DATE                datetime64[ns]
TIME                        object
PICK UP ADDRESS             object
pickup_datetime     datetime64[ns]
pickup_date                 object
pickup_time                 object
pickup_hour                  int32
pickup_minute                int32
pickup_second                int32
pickup_day                   int32
pickup_month                 int32
pickup_year                  int32
pickup_weekday               int32
pickup_week                 UInt32
pickup_quarter               int32
pickup_dayofyear             int32
is_weekend                    bool
dtype: object

 Missing values after cleaning: {df.isnull().sum()}

 Duplicate rows after cleaning: {df.duplicated().sum()}

 Sample Transformed Dataset:
        DATE      TIME     pickup_datetime pickup_date pickup_time  \
0 2014-07-01  00:00:00 2014-07-01 00:00:00  2014-07-01    00:00:00
1 2014-07-01  00:01:00 2014-07-01 00:01:00  2014-07-01    00:01:00
2 2014-07-01  00:01:00 2014-07-01 00:01:00  2014-07-01    00:01:00
3 2014-07-01  00:01:00 2014-07-01 00:01:00  2014-07-01    00:01:00
4 2014-07-01  00:02:00 2014-07-01 00:02:00  2014-07-01    00:02:00

   pickup_hour  pickup_minute  pickup_second  pickup_day  pickup_month  \
0            0              0              0           1             7
1            0              1              0           1             7
2            0              1              0           1             7
3            0              1              0           1             7
4            0              2              0           1             7

   pickup_year  pickup_weekday  pickup_week  pickup_quarter  pickup_dayofyear  \
0         2014               1           27               3               182
1         2014               1           27               3               182
2         2014               1           27               3               182
3         2014               1           27               3               182
4         2014               1           27               3               182

   is_weekend
0       False
1       False
2       False
3       False
4       False

In [51]:
print(cleaned_df.shape)
print(cleaned_df.columns.tolist())

(91124, 17)
['DATE', 'TIME', 'PICK UP ADDRESS', 'pickup_datetime', 'pickup_date', 'pickup_time', 'pickup_hour', 'pickup_minute', 'pickup_second', 'pickup_day', 'pickup_month', 'pickup_year', 'pickup_weekday', 'pickup_week', 'pickup_quarter', 'pickup_dayofyear', 'is_weekend']

In [52]:
print(cleaned_df["pickup_hour"].value_counts().sort_index())

pickup_hour
0     4552
1     3617
2     2645
3     2171
4     2271
5     2484
6     3004
7     5010
8     5215
9     4423
10    3534
11    3071
12    3172
13    3346
14    3422
15    3501
16    3829
17    3843
18    3880
19    4277
20    4672
21    4858
22    4939
23    5388
Name: count, dtype: int64

In [54]:
cleaned_df

,DATE,TIME,PICK UP ADDRESS,pickup_datetime,pickup_date,pickup_time,pickup_hour,pickup_minute,pickup_second,pickup_day,pickup_month,pickup_year,pickup_weekday,pickup_week,pickup_quarter,pickup_dayofyear,is_weekend
0,2014-07-01,00:00:00,"874 E 139th St Mott Haven, BX",2014-07-01 00:00:00,2014-07-01,00:00:00,0,0,0,1,7,2014,1,27,3,182,False
1,2014-07-01,00:01:00,"628 E 141st St Mott Haven, BX",2014-07-01 00:01:00,2014-07-01,00:01:00,0,1,0,1,7,2014,1,27,3,182,False
2,2014-07-01,00:01:00,"601 E 156th St South Bronx, BX",2014-07-01 00:01:00,2014-07-01,00:01:00,0,1,0,1,7,2014,1,27,3,182,False
3,2014-07-01,00:01:00,"708 E 138th St Mott Haven, BX",2014-07-01 00:01:00,2014-07-01,00:01:00,0,1,0,1,7,2014,1,27,3,182,False
4,2014-07-01,00:02:00,"700 E 140th St Mott Haven, BX",2014-07-01 00:02:00,2014-07-01,00:02:00,0,2,0,1,7,2014,1,27,3,182,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91707,2014-09-30,23:47:00,"593 Oak Ter Mott Haven, BX",2014-09-30 23:47:00,2014-09-30,23:47:00,23,47,0,30,9,2014,1,40,3,273,False
91708,2014-09-30,23:48:00,"645 Westchester Ave South Bronx, BX",2014-09-30 23:48:00,2014-09-30,23:48:00,23,48,0,30,9,2014,1,40,3,273,False
91709,2014-09-30,23:51:00,"625 Tinton Ave South Bronx, BX",2014-09-30 23:51:00,2014-09-30,23:51:00,23,51,0,30,9,2014,1,40,3,273,False
91710,2014-09-30,23:54:00,"350 Saint Anns Ave Mott Haven, BX",2014-09-30 23:54:00,2014-09-30,23:54:00,23,54,0,30,9,2014,1,40,3,273,False
91711,2014-09-30,23:58:00,"846 Tinton Ave Morrisania, BX",2014-09-30 23:58:00,2014-09-30,23:58:00,23,58,0,30,9,2014,1,40,3,273,False

In [55]:
hourly_pickups = (
    cleaned_df.groupby("pickup_hour")
    .size()
    .reset_index(name="pickup_count")
    .sort_values("pickup_hour")
)

display(hourly_pickups)

    pickup_hour  pickup_count
0             0          4552
1             1          3617
2             2          2645
3             3          2171
4             4          2271
5             5          2484
6             6          3004
7             7          5010
8             8          5215
9             9          4423
10           10          3534
11           11          3071
12           12          3172
13           13          3346
14           14          3422
15           15          3501
16           16          3829
17           17          3843
18           18          3880
19           19          4277
20           20          4672
21           21          4858
22           22          4939
23           23          5388

In [56]:
hourly_pickups = (
    cleaned_df.groupby("pickup_hour")
    .size()
    .reset_index(name="pickup_count")
    .sort_values("pickup_hour")
)

display(hourly_pickups)

    pickup_hour  pickup_count
0             0          4552
1             1          3617
2             2          2645
3             3          2171
4             4          2271
5             5          2484
6             6          3004
7             7          5010
8             8          5215
9             9          4423
10           10          3534
11           11          3071
12           12          3172
13           13          3346
14           14          3422
15           15          3501
16           16          3829
17           17          3843
18           18          3880
19           19          4277
20           20          4672
21           21          4858
22           22          4939
23           23          5388